# --------------------------------------- 
# Module: https
# Adds HTTPS protocol support to the TLS(SSL) Connector
# --------------------------------------- 
--module=https

## Connector host/address to bind to
jetty.https.host=0.0.0.0

## Connector port to listen on
jetty.https.port=9443

## Connector idle timeout in milliseconds
jetty.https.idleTimeout=30000
