galaxy_info:
  author: Mark Kusch
  description: Library like YAML and Python code
  company: http://silpion.de
  issue_tracker_url: http://github.com/silpion/ansible-lib/issues
  license: Apache 2
  min_ansible_version: 2.0.0.2
  github_branch: master
  platforms:
  - name: EL
    versions:
    - all
  - name: GenericUNIX
    versions:
    - all
    - any
  - name: Solaris
    versions:
    - all
  - name: Fedora
    versions:
    - all
  - name: opensuse
    versions:
    - all
  - name: Amazon
    versions:
    - all
  - name: GenericBSD
    versions:
    - all
    - any
  - name: FreeBSD
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  - name: SLES
    versions:
    - all
  - name: GenericLinux
    versions:
    - all
    - any
  - name: Debian
    versions:
    - all
  galaxy_tags:
  - lib
  - library
dependencies: []
