- name: Install add-apt-repostory
  sudo: yes
  apt: name=software-properties-common state=latest

- name: Add Oracle Java Repository
  sudo: yes
  apt_repository: repo='ppa:webupd8team/java'

- name: Accept Java 8 License
  sudo: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Oracle Java 8
  sudo: yes
  apt: name={{item}} state=latest
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default
- set_fact: java_home="/usr/lib/jvm/java-8-oracle/"