spring.jmx.enabled: false

server:
  servletPath: /*
  port: 8081
  
zuul:
  routes:
    root: /**
  include-debug-header: true
#not
  connections.max: 100
  connections.perroute.max: 10


management:
  context-path: /management

endpoints:
  dump.enabled: false
  shutdown.enabled: false
  health.sensitive: false

#overwritten by logback settings
logging:
  level:
    org.springframework.cloud.netflix.zuul: "DEBUG"
    net.coinshome.edge: "DEBUG"
    org.frontcache: "DEBUG"