---
# Download Oracle Java
#
# Installing Java while fetching the distribution from Oracle is
# a nightmare.
#
# Version information is a huge mess with Oracle Java. Naming of
# files, directories and zip archives is never consistent and one
# never knows what they are up to next.
#
# What this does is trying to use Ansible capabilities while
# allowing a re-usable installation of the Oracle Java JDK.


# Downloaded archives are verified with shasum command
- name: Register shasum binary
  tags:
    - java
    - java_download
  become: "{{ util_local_action_become_enable|default(omit) }}"
  become_user: "{{ util_local_action_become_user|default(omit) }}"
  become_method: "{{ util_local_action_become_method|default(omit) }}"
  changed_when: false
  register: java_registered_shasum_binary
  when: java_shasum_binary in (None, "")
  always_run: true
  with_first_found: "{{ java_shasum_binaries }}"
  local_action: command true

- name: Configure shasum binary
  tags:
    - java
    - java_download
  become: "{{ util_local_action_become_enable|default(omit) }}"
  become_user: "{{ util_local_action_become_user|default(omit) }}"
  become_method: "{{ util_local_action_become_method|default(omit) }}"
  always_run: true
  local_action: set_fact
  args:
    java_fact_shasum_binary: "{{ java_shasum_binary if java_shasum_binary not in (None, '') else java_registered_shasum_binary.results.0.item }}"


- name: Install Java redis packages sha256sum files
  tags:
    - java
    - java_download
  become: "{{ util_local_action_become_enable|default(omit) }}"
  become_user: "{{ util_local_action_become_user|default(omit) }}"
  become_method: "{{ util_local_action_become_method|default(omit) }}"
  local_action: template
  args:
    src: sha256sum.j2
    dest: "{{ lib_persistent_data_path_local }}/java-{{ java_oracle_version }}-{{ java_oracle_distribution }}.sha256sum"
    mode: 0644

# Test whether we need to download Java (again).
- name: Verify Java redis package sha256sum
  tags:
    - java
    - java_download
  become: "{{ util_local_action_become_enable|default(omit) }}"
  become_user: "{{ util_local_action_become_user|default(omit) }}"
  become_method: "{{ util_local_action_become_method|default(omit) }}"
  ignore_errors: true
  failed_when: false
  changed_when: false
  register: java_oracle_redis_exists
  always_run: true
  local_action: command
    {{ java_fact_shasum_binary }}
      --check
      --status
      {{ '--algorithm 256' if java_fact_shasum_binary|search('shasum') else '' }}
      {{ lib_persistent_data_path_local }}/java-{{ java_oracle_version }}-{{ java_oracle_distribution }}.sha256sum

# Ensure there is no broken download on the local disk
- name: Remove possible broken Java redis package
  tags:
    - java
    - java_download
  become: "{{ util_local_action_become_enable|default(omit) }}"
  become_user: "{{ util_local_action_become_user|default(omit) }}"
  become_method: "{{ util_local_action_become_method|default(omit) }}"
  when: java_oracle_redis_exists.rc != 0
  with_items:
    - "{{ lib_persistent_data_path_local }}/{{ java_oracle_redis_filename }}"
    - "{{ lib_persistent_data_path_local }}/{{ java_oracle_redis_jce_filename }}"
  local_action: file
  args:
    state: absent
    dest: "{{ item }}"


# Download the Java distribution from Oracle to the workstations'
# filesystem. Yeah, right, accept license agreement...
# This allows to distribute Java to any number of hosts in the
# context of a local network instead of downloading Java again
# for every role/node which depends on this role.
- name: Download Oracle Java redis packages
  tags:
    - java
    - java_download
  become: "{{ util_local_action_become_enable|default(omit) }}"
  become_user: "{{ util_local_action_become_user|default(omit) }}"
  become_method: "{{ util_local_action_become_method|default(omit) }}"
  register: java_oracle_redis_download
  when: java_oracle_redis_exists.rc != 0
  with_items:
    - { file: "{{ java_oracle_redis_filename }}", uri: "{{ java_oracle_redis_mirror }}" }
    - { file: "{{ java_oracle_redis_jce_filename }}", uri: "{{ java_oracle_mirror_jce }}/{{ java_oracle_redis_jce_filename }}" }
  local_action: command
    curl
      --location
      --insecure
      --remote-name
      --connect-timeout 4
      --retry 2
      --retry-delay 4
      --cookie oraclelicense={{ java_oracle_curl_cookie }}
      --cookie-jar /tmp/{{ java_oracle_redis_filename }}.cookie
      {{ item.uri }}
  args:
    chdir: "{{ lib_persistent_data_path_local }}"
    creates: "{{ lib_persistent_data_path_local }}/{{ item.file }}"

# Fixup possible users umask issues
- name: Ensure downloaded archives are world readable
  tags:
    - java
    - java_download
  become: "{{ util_local_action_become_enable|default(omit) }}"
  become_user: "{{ util_local_action_become_user|default(omit) }}"
  become_method: "{{ util_local_action_become_method|default(omit) }}"
  with_items:
    - "{{ java_oracle_redis_filename }}"
    - "{{ java_oracle_redis_jce_filename }}"
  local_action: file
  args:
    dest: "{{ lib_persistent_data_path_local }}/{{ item }}"
    mode: 0644

# Test whether downloaded redistributable package passes sha256sum
- name: Verify Oracle Java redis packages sha256sum
  tags:
    - java
    - java_download
  when: java_oracle_redis_download.changed
  become: "{{ util_local_action_become_enable|default(omit) }}"
  become_user: "{{ util_local_action_become_user|default(omit) }}"
  become_method: "{{ util_local_action_become_method|default(omit) }}"
  local_action: command
    {{ java_fact_shasum_binary }}
      --check
      --status
      {{ '--algorithm 256' if java_fact_shasum_binary|search('shasum') else '' }}
      {{ lib_persistent_data_path_local }}/java-{{ java_oracle_version }}-{{ java_oracle_distribution }}.sha256sum
