# -*- mode: ruby -*-

IP = "51.0.99.120"
NETWORK_MASK = "255.0.0.0"
NETWORK_GATEWAY = "51.0.0.1"
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.ssh.insert_key = true
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 1043, host: 1043
  config.vm.network "public_network", auto_config: false, :bridge => "eth0", ip: "#{IP}"
  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    v.cpus = 2
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  # Frontcache Server.
  config.vm.define "frontcache" do |logs|
    logs.vm.hostname = "frontcache"
    #logs.vm.network :private_network, ip: "192.168.9.90"

    logs.vm.provision :ansible do |ansible|
      ansible.playbook = "provisioning/frontcache/playbook.yml"
      ansible.inventory_path = "provisioning/frontcache/inventory"
      ansible.sudo = true
      ansible.extra_vars =
        {
            machine: "main",
            public_ip: IP,
            public_mask: NETWORK_MASK,
            public_gateway: NETWORK_GATEWAY,
            hostname: "frontcache",
            ansible_python_interpreter:"/usr/bin/python2.7" 
        }
    end
  end
end
