---
galaxy_info:
  author: Mark Kusch
  description: Role for base configuration of Ansible roles developed at Silpion.
  company: http://silpion.de
  license: Apache 2
  min_ansible_version: 2.0.0.2
  platforms:
  - name: EL
    versions:
    - 6
  - name: Fedora
    versions:
    - 20
  - name: Ubuntu
    versions:
    - trusty
  - name: Debian
    versions:
    - wheezy
  - name: Archlinux
    versions:
    - all
  categories:
  - system
dependencies:
  - src: "https://github.com/silpion/ansible-lib"
    name: silpion.lib
