---
# Ansible playbook for an Frontcache
#
#  
- hosts: all
  gather_facts: False 
  tasks: 
    - name: apt-get update 
      raw: apt-get update -qq 
    - name: Install python 2.7 
      raw: apt-get install -qq python2.7
    - name: Install mc 
      raw: apt-get install -qq mc
  
- hosts: all
  gather_facts: yes


  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=86400

  tasks:
    - lineinfile: dest=/etc/hosts regexp='ubuntu-xenial' line='127.0.0.1 ubuntu-xenial'       state=present
    - lineinfile: dest=/etc/hosts regexp='{{hostname}}' line='127.0.0.1 {{hostname}}' state=present
    - shell: sudo bash -c 'hostnamectl set-hostname {{hostname}}'
    #- name: stop eth1
     # shell: ifdown eth1
     # ignore_errors: yes

    - name: set networking
      template: src="files/interfaces/eth1.cfg.j2" dest="/etc/network/interfaces.d/eth1.cfg"

- name: Install Java 8u66 JDK to /opt/java
  hosts: all
  roles:
  - role: groover.java
    oracle_java_distribution: jdk

- name: Install Apache Tomcat
  hosts: all
  roles:
    - role: groover.tomcat    

- name: Install Frontcache
  hosts: all
  roles:
    - role: frontcache.app